# Generated by Django 5.2.7 on 2025-11-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_admin_reply_complaint_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='admin_reply',
            new_name='reply',
        ),
    ]
