# Generated by Django 5.2.7 on 2025-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_rename_admin_reply_complaint_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='date_submitted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
