# Generated by Django 5.2.7 on 2026-01-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_status_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='complaint',
            name='emotion_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='stress_score',
            field=models.FloatField(default=0.0),
        ),
    ]
